language: go
go:
  - "1.10"

services:
  - mongodb

go_import_path: github.com/BeyondBankingDays/minions-api

script: # the build step
  - go test -v ./...
  - CGO_ENABLED=0 go build -o ./build/api cmd/main.go

cache:
  directories:
    - "$HOME/google-cloud-sdk/"
after_success:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  - gcloud --quiet components update kubectl
  # Auth flow
  - echo $GCLOUD_KEY | base64 --decode > /home/travis/gcloud.json
  - gcloud auth activate-service-account $GCLOUD_EMAIL --key-file /home/travis/gcloud.json
  - ssh-keygen -f ~/.ssh/google_compute_engine -N ""
  # Push to Google container registry
  - docker build -t eu.gcr.io/bb-hackathon/api:$TRAVIS_COMMIT .
  - gcloud container clusters get-credentials hackathon
  - gcloud docker -- push eu.gcr.io/bb-hackathon/api:$TRAVIS_COMMIT
  - if [ "master" == $TRAVIS_BRANCH ]; then kubectl set image deployment/api api=eu.gcr.io/bb-hackathon/api:$TRAVIS_COMMIT; fi
